sonar.projectKey=dudeakira6-art_Doncrepe
sonar.organization=dudeakira6-art

# Nombre y version visibles en SonarCloud
sonar.projectName=Doncrepe
sonar.projectVersion=1.0

# Rutas del codigo fuente
sonar.sources=src
sonar.tests=test

# Codificacion
sonar.sourceEncoding=UTF-8
