sonar.projectKey=dudeakira6-art_Doncrepe
sonar.organization=dudeakira6-art

# Nombre y version visibles en SonarCloud
sonar.projectName=Doncrepe
sonar.projectVersion=1.0

# Rutas del codigo fuente
sonar.sources=src
sonar.tests=test
sonar.java.binaries=build/classes
sonar.java.test.binaries=build/test/classes
sonar.java.libraries=lib/**/*.jar
sonar.java.test.libraries=lib/**/*.jar
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacoco.xml

# Codificacion
sonar.sourceEncoding=UTF-8
